---
- name: Exercise 3a
  hosts: nxos
  gather_facts: false
  tasks:
    - name: Gather show version output
      cisco.nxos.nxos_command:
        commands: show version
      register: show_version

    - ansible.builtin.debug:
        var: show_version
