---
- name: Exercise 3a
  hosts: nxos
  gather_facts: false
  tasks:
    - name: Gather show version output
      cisco.nxos.nxos_command:
        commands:
          - show lldp neighbors
      register: show_commands

    - ansible.builtin.debug:
        var: show_commands["stdout_lines"][1]
